### ISSUE TITLE
[FEATURE] <shelter> global improvement

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/unhcr-geneva-tech-hub-app#232]
- [x] env performance colors: https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/130
- [x] the filtering by year is not working anymore on the listing of the shelters (some documents did not have created_at field)
- [x] fix filtering by region for projects/users in Overview

- [x] the http// error for	the DELETE part	should not be an error for 204;
     - [x]  Delete not working (@andreullal  by the way, it's working; I just have a cache of 24h; that's why the image was still accessible; I can remove it; But I think it's better to keep it. and it's not a problem)
- [x] Download button behave as the link --> and we should	download the original_url image and not	the webp

- [x] -> better title for shelter
- [x] -> fix the compare view #197

- [x]  the total report (project name) #85
    - [x]  the button at the top of scorecard —> rename export assessment report
    - [x] the goal is to remove/hide that extra page
    - [x] For the assessment report, don't need to have the table details (don't expand per material)

- [x]  two days for the other reporst (boq + compare report?)
    - [x]  reduce the size of the titles (font-size to 9) // minimum 8pt
    - [x] Don't repeat the total for each page (show a 'to continue', if we split)
    - [x] Repeat the headers of the table
    - [x] Hide the actions
    - [x] Hide the 'Items' text from the table 
    - [x] overall better print
- [x] scorecad rescaling: https://github.com/EPFL-ENAC/unhcr-geneva-tech-hub-app/issues/207
- [x] Overview -> check that habitability data is displayed with percentage
- [x] Overview projects -> aggregation per year work as it supposed to
- [x] shelter listing; be sure top align horizontally /center vertically the text
- [x] shelter listing make the map:     height: 400px;

**Comment by guilbep** [comment]
I'm closing this issue since everything important is done or open in other issues
