### ISSUE TITLE
New constants from EPIC database (instead of ICE and EcoInvent)

### ISSUE THREAD

**Issue by andreullal** [EPFL-ENAC/unhcr-geneva-tech-hub-app#80]
- [x] Update json export file with new coefficients from EPIC database @andreullal 
- [x] Reload json file with new constants @guilbep 
- [x] Make embodied water constants visible again in materials tab of database (previosuly removed pending discussions with EcoInvent)

**Comment by andreullal** [comment]
@guilbep 
I've updated material constants in the Gsheet. Please Reload the json file - ideally, as part of the Phase 1 version to be released to UNHCR tomorrow.

**Comment by guilbep** [comment]
Deployed in 0.1.8 release
